name: "Secure AI Scanner"
description: "AI-powered Multi-language security scanner"
author: "Srivatsa"

branding:
  icon: shield
  color: purple

inputs:
  github_token:
    description: "GitHub token for posting PR comments (requires pull-requests: write permission)"
    required: true

  scan_path:
    description: "Path to scan within the repository (supports multi-language projects)"
    required: false
    default: "."

  enforce_policy:
    description: "Enforce security policy: block push if HIGH severity issues >= 25% threshold"
    required: false
    default: "false"

  groq_api_key:
    description: "Groq API key for optional AI-powered analysis (uses pattern-based fallback if not provided)"
    required: false
    default: ""

permissions:
  contents: read
  pull-requests: write
  security-events: write
  statuses: write  # Required to set commit status checks

runs:
  using: "docker"
  image: "Dockerfile"
 

  args:
    - ${{ inputs.scan_path }}
    - ${{ inputs.github_token }}
