name: "AI-Vulnerability-Scanner"
description: "Scan code, generate AI summary, produce SARIF, and post PR comments."
author: "Sri"

branding:
  icon: shield
  color: purple

inputs:
  github_token:
    description: "GitHub token for posting PR comments"
    required: true
  scan_path:
    description: "Path to scan"
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.scan_path }}

permissions:
  contents: read
  pull-requests: write
  security-events: write
