name: "AI-Security-Scanner"
description: "Multi-language security scanner with AI-powered analysis for Python, JavaScript, Java, and Go projects. Includes policy enforcement, dashboard reports, and PR integration."
author: "Sri"

branding:
  icon: shield
  color: purple

inputs:
  github_token:
    description: "GitHub token for posting PR comments (requires pull-requests: write permission)"
    required: true

  scan_path:
    description: "Path to scan within the repository (supports multi-language projects)"
    required: false
    default: "."

  enforce_policy:
    description: "Enforce security policy: block push if HIGH severity issues >= 25% threshold"
    required: false
    default: "false"

permissions:
  contents: read
  pull-requests: write
  security-events: write

runs:
  using: "docker"
  image: "Dockerfile"

  args:
    - ${{ inputs.scan_path }}
    - ${{ inputs.github_token }}
