name: "AI-Vulnerability-Scanner"
description: "Scan code, generate AI summary, produce SARIF, and post PR comments."
author: "Sri"

branding:
  icon: shield
  color: purple

inputs:
  github_token:
    description: "GitHub token for posting PR comments"
    required: true
  scan_path:
    description: "Path to scan"
    required: false
    default: "."

permissions:
  contents: read
  pull-requests: write
  security-events: write

runs:
  using: "docker"
  image: "Dockerfile"

  # Pass inputs into container:
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}

  args:
    - ${{ inputs.scan_path }}
    - ${{ inputs.github_token }}
