#!/usr/bin/env python3
"""
pr_commenter.py

Posts an AI-generated summary as a GitHub PR comment.

Features:
- Clean Markdown formatting
- Severity-based formatting (GitHub-safe)
- Robust error handling
- No hallucinated links or content
"""

import argparse
import os
import requests
from pathlib import Path


# -----------------------------------------------------
# Build Markdown comment body
# -----------------------------------------------------
def build_comment_body(summary_text: str) -> str:
    return f"""
## 🔍 AI Security Scan Summary

This is an automated security summary generated from **Bandit**, **Semgrep**, and **pip-audit** results.

---

### 🧠 **Summary**

---

### 📌 Notes
- This summary is **fully AI-generated**, but based strictly on the scanner output.
- No external assumptions or fabricated references are included.
- Please validate issues before making code changes.

---

🙌 *Generated by the AI Vulnerability Scanner*
"""


# -----------------------------------------------------
# Post PR comment via GitHub API
# -----------------------------------------------------
def post_comment(repo: str, pr_number: str, token: str, comment: str):
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }

    resp = requests.post(url, headers=headers, json={"body": comment})

    if resp.status_code >= 300:
        raise Exception(
            f"GitHub API error: {resp.status_code} {resp.text}"
        )

    print(f"💬 Successfully posted PR comment on #{pr_number}")


# -----------------------------------------------------
# Main
# -----------------------------------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", required=True, help="Path to summary.txt")
    parser.add_argument("--repo", required=True, help="owner/repo")
    parser.add_argument("--pr", required=True, help="Pull request number")
    parser.add_argument("--token", required=False, help="GitHub token")

    args = parser.parse_args()

    # GitHub Token (fallback to env)
    token = args.token or os.environ.get("GITHUB_TOKEN")

    if not token:
        raise Exception("❌ GitHub token not provided (set GITHUB_TOKEN or use --token).")

    summary_path = Path(args.summary)
    if not summary_path.exists():
        raise FileNotFoundError(f"❌ Summary file not found: {summary_path}")

    summary = summary_path.read_text(encoding="utf-8")

    # Build the final comment
    comment_body = build_comment_body(summary)

    # Post it
    post_comment(args.repo, args.pr, token, comment_body)


if __name__ == "__main__":
    main()
